DELETE http://localhost:3003/api/blogs/6137b1ba0cd36c5cd0419356
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpwaW4iLCJpZCI6IjYxMzc5OWNlYjVmZDlhNTc4MjljNjYyNyIsImlhdCI6MTYzMTA0MTE0OCwiZXhwIjoxNjMxMDQ0NzQ4fQ.QDHp4bWDGl46xOSqfxSX6WEdCUoSoSAaR7hfjWF49W0